name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - pandas
    - requests
    - GEOS==3.3.3
    - PROJ==6.*
    - cartopy
    - ipywidgets
    - matplotlib
