name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - pandas
    - requests
    - GEOS
    - PROJ
    - cartopy
    - ipywidgets
    - matplotlib
